services:

  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    container_name: alpip-backend
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=development
    volumes:
      - ./backend:/app


  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    container_name: alpip-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    volumes:
      - ./frontend:/app
